### ISSUE TITLE
Roadmap to v2

### ISSUE THREAD

**Issue by oschwald** [oschwald/maxminddb-golang#141]
- [ ] Replace `net.IP` and `*net.IPNet` with `netip.Addr` and `netip.Prefix`
- [ ] Update naming and docs to more closely align with `net/netip`
- [ ] Make `SkipAliasedNetworks` the default when traversing a tree. Almost no one wants the IPv4 information to be repeated in several spots
- [ ] Replace `LookupOffset` with method that returns a struct rather than a `uintptr`. The returned value would have a `Decode(any)` method to replace the current use of `(*Reader).Decode`. Beyond the type safety and reducing the risk of a panic due to programmer error, this would provide the ability to do things like a `DecodePath(result any, path ...any)` that could avoid the use of reflection or creating a struct to decode to when looking up a single value.
- [ ] `(*Reader) Decode` is removed. See above.
- [ ] After the above changes, reexamine the `Lookup*` methods. Do we really need `Lookup`, `LookupNetwork`, and `LookupOffset` (or whatever the above replacement will be called)? Maybe the `LookupOffset` method could replace all of them, although we would have to think about how error handling would work so as not to make it more verbose (e.g., defer returning error from the tree lookup).
- [ ] Maybe rename `FromBytes` to `OpenBytes` or something as many people seem to overlook it.
- [ ] Move decoder to a separate package to make PRs like [this one](https://github.com/oschwald/maxminddb-golang/pull/91) more viable without creating a mess of the `maxminddb` package.

**Comment by oschwald** [comment]
I have started this in [`v2` branch](https://github.com/oschwald/maxminddb-golang/tree/v2).

**Comment by oschwald** [comment]
I've release `v2.0.0-beta.1`. As mentioned in the release notes, I expect a final v2 release to be available after Go 1.24 is released. I've made most of the anticipated breaking changes, but it is likely there will be new breaking changes based on feedback.

**Comment by oschwald** [comment]
There are no known issues with it. It is possible there may still be breaking changes before the final release, although I suspect any breaking changes from here on out with be limited to less used features or the new `Unmarshaler` API.
